#!/bin/sh

# Run sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setup screens
xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of DP-2 && sleep 0.3

bspc wm --reorder-monitors DP-2 DP-1

# assign desktops
bspc monitor DP-2 -d main 2 3 4
bspc monitor DP-1 -d 5 6 chat music

bspc monitor DP-2 -f

# Bspc config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Desktop config


# Desktop 7 - Communicators
bspc rule -a discord desktop='^7'

# Desktop 8 - Music players
bspc rule -a Spotify desktop='^8'
bspc rule -a com.github.th_ch.youtube_music desktop='^8'

# Launch scripts
~/.config/polybar/launch.sh &
~/.config/picom/launch.sh &
~/.config/feh/launch.sh &
~/bin/launch.sh &
